sonar.projectKey=nextjs-app-router-boilerplate
sonar.projectName=Next.js App Router Boilerplate
sonar.projectVersion=1.0

# Source & Test paths
sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.tsx,**/*.spec.ts,e2e/**/*.spec.ts

# Exclusions
sonar.exclusions=src/locales/**,**/*instrumentation*.ts,node_modules/**,.next/**,out/**,build/**,coverage/**,test-results/**,playwright-report/**,blob-report/**

# Metadata & Settings
sonar.sourceEncoding=UTF-8
